[[redirects]]
  from = "https://blog.zeppelinos.org/*"
  to = "https://blog.openzeppelin.com/:splat"
  status = 301

[[redirects]]
  from = "https://crafty.zeppelin.solutions/*"
  to = "https://crafty.openzeppelin.com/"
  status = 301

[[redirects]]
  from = "https://forum.openzeppelin.org/*"
  to = "https://forum.openzeppelin.com/:splat"
  status = 301

[[redirects]]
  from = "https://forum.zeppelin.solutions/*"
  to = "https://forum.openzeppelin.com/:splat"
  status = 301

[[redirects]]
  from = "https://zepkit.zeppelinos.org/*"
  to = "https://openzeppelin.com/starter-kits"
  status = 301

[[redirects]]
  from = "https://docs.defender.openzeppelin.com/*"
  to = "https://www.notion.so/openzeppelin/Defender-Docs-f3c1b455389a4d88af7f2e6623f6e1ba"
  status = 302
